const Products = [
    {
        id: 1,
        image: './images/feature/item-00.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'Smartfóny',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 2,
        image: './images/feature/item-01.jpg',
        hoverImg: './images/feature/item-002.png',
        name: 'Samsung Galaxy S22',
        category: 'Smartfóny',
        price: '999 €',
        wishlist: 'Add to Wishlist',
    },
    {
        id: 3,
        image: './images/feature/item-02.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'Samsung Galaxy S22',
        category: 'Smartfóny',
        price: '999 €',
        wishlist: 'Add to Wishlist',
    },
    {
        id: 4,
        image: './images/feature/item-00.jpg',
        hoverImg: './images/feature/item-002.png',
        name: 'Samsung Galaxy S22',
        category: 'Smartfóny',
        price: '999 €',
        wishlist: 'Add to Wishlist',
    },

    {
        id: 5,
        image: './images/feature/item-01.jpg',
        hoverImg: './images/feature/item-002.png',
        name: 'Samsung Galaxy S22',
        category: 'Featured',
        price: '999 €',
        wishlist: 'Add to Wishlist',
    },
    {
        id: 6,
        image: './images/feature/item-02.jpg',
        hoverImg: './images/feature/item-002.png',
        name: 'Airpod S22',
        category: 'Airpods',
        price: '999 €',
        wishlist: 'Add to Wishlist',
    },
    {
        id: 7,
        image: './images/feature/item-00.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'Smartfone1',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 8,
        image: './images/feature/item-00.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'iphone-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 9,
        image: './images/feature/item-00.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'iphone-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 10,
        image: './images/feature/item-00.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'iphone-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 11,
        image: './images/feature/item-00.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'iphone-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 12,
        image: './images/feature/item-01.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'desktop-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 13,
        image: './images/feature/item-01.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'desktop-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 14,
        image: './images/feature/item-01.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'desktop-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 15,
        image: './images/feature/item-01.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'desktop-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 16,
        image: './images/feature/item-02.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'airpods-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 17,
        image: './images/feature/item-02.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'airpods-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 18,
        image: './images/feature/item-02.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'airpods-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
    {
        id: 19,
        image: './images/feature/item-02.jpg',
        hoverImg: './images/feature/item-001.png',
        name: 'iPhone 17 PRO (2023)',
        category: 'airpods-4',
        price: '1299 €',
        wishlist: 'Add to Wishlist',
        dis_percentage: '-39%',
        item_brand: 'Novinka',
    },
];

export default Products;
